// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQ_ZsknGJyBSrDbZzk6OAIYI3SKaGzrY',
    appId: '1:471131935789:web:327df2632b55ff725114a4',
    messagingSenderId: '471131935789',
    projectId: 'fir-meetup-94dcc',
    authDomain: 'fir-meetup-94dcc.firebaseapp.com',
    storageBucket: 'fir-meetup-94dcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgx7PJXvHidb7JEJoPRysDCtmQcmpjjEw',
    appId: '1:471131935789:android:0f0c02349d6cb9d75114a4',
    messagingSenderId: '471131935789',
    projectId: 'fir-meetup-94dcc',
    storageBucket: 'fir-meetup-94dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-gBaUpuW8Z9pxqatSxq_QXHoGA-yKs8Y',
    appId: '1:471131935789:ios:778fb231228177f85114a4',
    messagingSenderId: '471131935789',
    projectId: 'fir-meetup-94dcc',
    storageBucket: 'fir-meetup-94dcc.appspot.com',
    iosBundleId: 'com.example.meetupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-gBaUpuW8Z9pxqatSxq_QXHoGA-yKs8Y',
    appId: '1:471131935789:ios:d650db13bb101b0b5114a4',
    messagingSenderId: '471131935789',
    projectId: 'fir-meetup-94dcc',
    storageBucket: 'fir-meetup-94dcc.appspot.com',
    iosBundleId: 'com.example.meetupApp.RunnerTests',
  );
}
